apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
    annotations:
        description: Cloudflare API token for cert-manager DNS-01. Zone:DNS:Edit for the lucawahlen.com zone only.
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:GFhaoAOR6pWcWvlyDsa9WaL0+OUf1rLpi/UGS9VmUwMysy02IZVNa0q3DQZYoA6EYiXytzs=,iv:Z5vI1eNx3uik542RdIs+Yet6xbDVDp6XVOS3rbwTlk0=,tag:buacWWnOflnKAqdYYaoXow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3V2NqREM3SjJPVHZTdVR6
            U3hVaDVvdGdSa3hyVHRKclliQVFCNWVidG1rCmgyUjh3L0NBcG1SRUc5WFFpd1pN
            Si80ODA2KzNCM1pIVkNNdm5UaW82N3MKLS0tIHhuWVJJUTM4NzJVZ1hHbFlIUE84
            bFlycnppU1FFMGtBQkllMU9VV09qd3MK0IeeyOOxzJjqQQX/SEGgKzgYoHBeYiOY
            wskGHrKShzltahKBBZRr9Obz5h0vhIzFST/whsTf6+7UGoYwCistqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwn0l05325gc4p827dgqw5s0k38an0cuum87pj2359ugyd0rhc6s50yqn9
    lastmodified: "2026-09-27T15:22:37Z"
    mac: ENC[AES256_GCM,data:aA8Un+LkTO0oEuVvciT+JEvj/Y2cneR7HZ1MLPD/IRFL50MHDtnAilJPZ0i5/lzJQKLb+vBHlIBsgEhqZC3qyFq5c77Nasv/ZDV8Y8t1cmjxdYOXzfNF/mADKBRt29qg3U6SPnn4UcSwcC9NPEp1axmChThres0Nddu7BSBNu68=,iv:UZN7u4Ygg3Hqh524NC7OJNxHHNRzXcf4zNUgM5LpxSg=,tag:9qe8+b73RQSVNxIvfL9ozQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
