apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
    annotations:
        description: Cloudflare API token for cert-manager DNS-01. Zone:DNS:Edit for the lucawahlen.com zone only.
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:58bsJbQ2AzJMpG+cSS+g98ue0glevF8QZ/vuUh5HHd8bpMe8GaLCRxAzf8vA3AzQmi4+rbg=,iv:oYBNJWpPLdL3++lLW5ijtN9da6ZsZwv1enGtU0Y8llw=,tag:BOru4Qyx7wL8VxwPYkZaBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3V2NqREM3SjJPVHZTdVR6
            U3hVaDVvdGdSa3hyVHRKclliQVFCNWVidG1rCmgyUjh3L0NBcG1SRUc5WFFpd1pN
            Si80ODA2KzNCM1pIVkNNdm5UaW82N3MKLS0tIHhuWVJJUTM4NzJVZ1hHbFlIUE84
            bFlycnppU1FFMGtBQkllMU9VV09qd3MK0IeeyOOxzJjqQQX/SEGgKzgYoHBeYiOY
            wskGHrKShzltahKBBZRr9Obz5h0vhIzFST/whsTf6+7UGoYwCistqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwn0l05325gc4p827dgqw5s0k38an0cuum87pj2359ugyd0rhc6s50yqn9
    lastmodified: "2026-09-26T14:28:09Z"
    mac: ENC[AES256_GCM,data:TXDt1MjmEqzgA8MuogrxvyNeWUqrP4Gpa5E4GG7VGxNZQ8P1P2XBq+9aWGXDrke2S1PHe86RblmEpeNAgcteu9x3j0XePJfx1ygMUE3FNl8X56PhVlmX/R07hFxpMVKTSNEoL0Kh34Uy9vhvHSNd6tJVA9m+WPWbVbwbaPfWu10=,iv:JdWnu3Vb0nBxru+zz5OXnydNZla+S25V3AAkXR7zKE8=,tag:3rl+FV6cVjcjadeLQSh21Q==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
