apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: halite
spec:
  ingressClassName: traefik
  rules:
    - host: halite.lucawahlen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: halite
                port:
                  number: 8080
