apiVersion: v1
kind: Secret
metadata:
    name: halite-admin
    namespace: halite
type: Opaque
stringData:
    HALITE_ADMIN_PASSWORD: ENC[AES256_GCM,data:GzIjbCgSG6PXpm4VzkmO6B7M1Jc=,iv:R+KD1s2tmaFPFJk/uV9p1UP0C5YglLrgUjQmkcPJFYU=,tag:OnVWK9EpQ0FTeZn0RAu25g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQmtwNjFaVWxqaUhRY3h5
            UE1mTlErS2RXaUtDZXpCdnMrelJjWnZFQlFzCklxcFhZd05LaTlpalhDT0tNR3Bl
            QmZ3QTJUbEd3M25qM1V4YzRvd2F3MGsKLS0tIFE2S001UkxPT2RicTdvRzFEWWQr
            Q2JBbWNMeERsVmVkYVFXQnhkUWloNEkKJpUxmUWJd7TiMTpaoOaMk/UcHYHVQQ61
            8dWgU60eSNjwJFF+wqv+dHqzY6aKxJcqaQ6rjdAsS/NbCNo1AFYUBQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwn0l05325gc4p827dgqw5s0k38an0cuum87pj2359ugyd0rhc6s50yqn9
    lastmodified: "2026-10-08T13:45:19Z"
    mac: ENC[AES256_GCM,data:cWt/iqzFQjdQTzniyK/LhB6Gd+4d8dLZpIdG8i3JaDn7v4TidUpkWPbpQWgumbdmEhZMFIAHxB0mK8r6tGyfPhDgZ6Qphez1vNtjCvDZoAbMZfCRAk01T42RSSUe7OApADhgIsu068wUZUFzmABrUF4VUrsK5LW0JSy1b59BPYc=,iv:zxlnsjQl16ZnSP3IDTk5YlYP0ZOVhzkHRUi0WqeeQIs=,tag:R4HMRpVni6T4izw71H3AvA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
