schema_version: 34
http:
  address: 0.0.0.0:3000
  session_ttl: 720h
users:
  - name: admin
    password: __ADGUARD_PASSWORD_HASH__
auth_attempts: 5
block_auth_min: 15
dns:
  bind_hosts:
    - 192.168.178.234
  port: 53
  upstream_dns:
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
  bootstrap_dns:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
  upstream_mode: parallel
filtering:
  protection_enabled: true
  filtering_enabled: true
  filters:
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
      name: AdGuard DNS filter
      id: 1
querylog:
  interval: 2160h
statistics:
  interval: 24h
dhcp:
  enabled: true
  interface_name: eth0
  local_domain_name: lan
  dhcpv4:
    gateway_ip: 192.168.178.1
    subnet_mask: 255.255.255.0
    range_start: 192.168.178.20
    range_end: 192.168.178.200
    lease_duration: 7200
    icmp_timeout_msec: 1000
    options: []
