apiVersion: v1
kind: Secret
metadata:
    name: adguard-credentials
    namespace: adguard
type: Opaque
stringData:
    password-hash: ENC[AES256_GCM,data:a3/dc7yirVS23EVmO0TuAevXHN2TPoMvVuRYKwJEmY25ZYFkjo0jm46xd049Qcf5Lt6/UbrtC/ueC9wc,iv:UFr4ohYqHoFEo0Kdb+UVKNntjBbBV+xvqW75dDA5hCw=,tag:HeCvWMooT1twKj2bDrdo8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTmM3bkNHRXBjMzc2YVg3
            Q2tIdUNaeFlnbE4wdzU4OWY1cGlodXBJbG00CjZHOUZzMU5WOVd2QlU4ZTRjeXdY
            S0ViRXdiSHZrSHlkSTRDNUFWaTA0UzgKLS0tIDZNR3pYRitPeDJQTWlUd2E4VXlR
            TmVTUzdjU0c0Z0thVWlsK0ZidXBnY0kKg0HQEkACPoJmEFNDAdtq+t5UXyexHYvv
            Ad+Qymbl70bC+KQIriYvVDkUQmAor0qsNbSGis8VKrxz7ChFZcn6WQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwn0l05325gc4p827dgqw5s0k38an0cuum87pj2359ugyd0rhc6s50yqn9
    lastmodified: "2026-09-11T11:21:30Z"
    mac: ENC[AES256_GCM,data:AdCJ/CNd9sVP1qKkCcUK4qyG14nV4ALGgKxHnkKxD9GXatNJzN+I2INURz52jmJaJlpna6c7VLQ0Lz9SIfyflW07B7KrbDZqG2k/8/fGvFkzzdEtdRQcUQIYLVyI0xfDz9XkF++HpUrCIkq8de7xTyQKLSa/B3aqPw+CFKG5L+w=,iv:4cKDAXXjxSBqr7NcV42162hQNMtXrel6ZSCJxmizqG8=,tag:fBT4kGdnjl8GnA4NaJ9qjw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
