apiVersion: v1
kind: Secret
metadata:
    name: adguard-credentials
    namespace: adguard
type: Opaque
stringData:
    password-hash: ENC[AES256_GCM,data:SKLOfjml8wJX0dXuzfygOSzFnaX4ND5kIft/mIMh4xhQ13Y4pc7jFJheKqT5uVAEQbKN4pI9SC34Cn7c,iv:QhvIYL+rWO7l/mfVNuwaxSbmgyG/caS1v9fSuvcl/hY=,tag:N8LZeJiAvhygzAhHDxfwkQ==,type:str]
    #ENC[AES256_GCM,data:MAWog6a05tLO4G8YtzNRWdix6xGEbwWvzaNniO7UAznlZ4UASqa+FPMWS6Wvy00Dqjs5hcOLSByLvVS48wdDsq4g9j4L,iv:qwDqGoAU6+bvTAdD89+YHbXjT7jui6YUqWu58j7oCCk=,tag:/YIU1dNw3GwnFOCuWqHK5w==,type:comment]
    #ENC[AES256_GCM,data:ELXUYnoYBfkVICm3JYg2JiAY4AwuTdw3smRvG97J5J1l9KWMKiFVBsM+mQPol1k=,iv:T689mCzM1bFcDn3MJrfUD/zTOHwjYsDUb2NtFYlZbuY=,tag:58nYE6MvowBpb3DXeEZZBA==,type:comment]
    #ENC[AES256_GCM,data:MfSNpRGDmrp9iv0FMC2I5nvaPe3snHY76iu5,iv:KkZJpAhA/rLujnUobQpj0bQY8Z1emesjytGUgZaQRPE=,tag:RlFH8UyJCIv5kVa+jyQ5bA==,type:comment]
    #ENC[AES256_GCM,data:iyppi83Rv4wOFY8XcP5YL8PxMjClz7E=,iv:65IiUiN5yl06jbBKvPsjeaN2izOJtzkIWzhyouKGL1w=,tag:LfzhB0Q5cSVndZObkUi/Sg==,type:comment]
    #ENC[AES256_GCM,data:2sMtlyTj/VY+J3TsEdS1TQ0tXGdueg==,iv:BFw+jT6XkUNbkQz25o67d1m1dT83NihK1fzqBi0BROw=,tag:DpIehwa4O5YUyAP97VJrZg==,type:comment]
    static-leases: ENC[AES256_GCM,data:zdO7D8pkVk8dyRnJWPTxHuAWNkOnKlLHdkv5PMMRv86/prVylHDjv+A+XBsZ1frhVXY3womLtp8QaFXjCpr4U3DbqzS8AFvhJw==,iv:kgMzoQjPq95I3x3LZIwlQyfsyZ45CPWxfv8LC1PE6Z8=,tag:zEm1q0LbslxVKCpDvclPQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YlRKcVdZOFdTUHphM2pL
            TWFwYVFrdkpIamQxWkFhNzdRQjg5M2w0dVMwCmhqZ2lxNEJ4bFl2K1dTMEk4STRh
            U0YwaGFZRStJQm1pSnl4aDZwWkJtbVkKLS0tIElWM3gzSDFsb0lIaWRYcnd5aUU5
            SjFTL0w0SjNwd1ZkaUVneEs2b2xBcFEK3/dhgvsEkYZEP/zuSx6TmvSAh/asEBRT
            Fft3KKZto8B0tCRA1mbYQWQ4vvRWywCjYoBpUDe7dcnJbqoLq1XMuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwn0l05325gc4p827dgqw5s0k38an0cuum87pj2359ugyd0rhc6s50yqn9
    lastmodified: "2026-09-11T14:54:16Z"
    mac: ENC[AES256_GCM,data:noHIMAgSO7kT3L2dvkTTXLH9kJ50+f+sKUkZTjP/1jze3Uy46szRegolEzR42E19UUb6bat0REOjBM4UT+21/Yuyi9sa4T/Cn2YRgqOtFiD/4eXBA3GC6F2ADY9zq/3Ss4RQbZjJn5e+rcrbqc+VtQViypwmzmykGTYO002JG5k=,iv:B1KDTwTM4FUfERSWY6aI/aAYLFGJjtpuzdFlscdpr2c=,tag:Q6oa6XySHmUDUpAeDCiM0Q==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
