apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:POgLs/JjmDbxsrzpkrBIGWKJDS8vxzwsBnyx3QkAQuhqpiwKxYzbIBZy1fFrb+oUwY+Xv3XW8djlA5roCBeAKU5OEHr9cxnda1c10yJeLGnmvyoUbrINaw4C43aSFc00MvhiIMDYE804b6AQV3AKCJqFRyqwQHv7iY10KG9ksdJC1MVMA+qPcUyc7Jo0XtT9zhMbB2lAI0ZuC1fzPVW2SlVlbq3GvlBad7LM/OfiOpArbS/8,iv:9Dk7bgwFMy2ffzuYEuxtnl5nXiZwX+PzTF9wnUuqd3o=,tag:HY3VEN7D8YRHxQsRuzMfnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTHdCdkZDOXRnc0VERUF6
            cDJUNElIMmU0aSt6TkdaYWdxSVZaUG5rQWd3CmVuN08vK3NyWEZTS2RDQmFRTFd3
            TGtCS3YycDZhek1uOVRxVVZrMDJvWncKLS0tIEtyNnJnd1hta2ZHOHgrRVBJOUhE
            ZnlKOGY5M1VEZ3RwUFl5QVAyTWp0SFUKZoQEfIIAkw7LVw2QJuMkg5/Ql6prOpdF
            wUr9AZSofGfbSpM3KYgq3W2Bhkpzp2FWsX6hRfsQJDHpHN5gEuwD4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwn0l05325gc4p827dgqw5s0k38an0cuum87pj2359ugyd0rhc6s50yqn9
    lastmodified: "2026-09-08T20:55:51Z"
    mac: ENC[AES256_GCM,data:DOoJ/MT5yjpAI+3NCU3+4D9fy95S3Z/YXgN/P8UyQJHIb++CR75XKQfqassROVfWdv4GP7S5Oi6jF+2/tTwF3HDzDg13sFZO9eVybtXIHU7nDvGHLIzcf6D2EUZJ1nmbHRDLiJfF/55wvk+VXUBT1e5ZKtdHXuNwsS9bT9sYUkI=,iv:XXZ11lFt19ID6hHLvFWenkTm3CGvREzOyu3wlRYeu0g=,tag:dxX8uc6cr+WC4YpAppmwWw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
