apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:hyH5V+tRy7Tf67ka5U7cpAWYLW7u3tFw3BLIkwJOnI4UeuiwlbJD6TtsGl4921IgWI3jW9qzisq9jjPToDnwKPjXxyunXUF4oPf7epatAxwfkV9HT/tQEBnYvdMQAEvHsWvJO9VUjKIfBNuUDOt3xH7hjterMjF3LIef4bYpQFNt72McShM3J36RjAtuJyvzsUNTyRoNK2KXQYjB6jcXwllF+gdPD88hAruB4cLLtcSza98o,iv:FwrxAnSnNW6AfJNCMuefX1AAZAyTftZkqT7j1SP3Cn8=,tag:ExYgwlVa8uBvi5YD7eDr8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUHp1bHArTUVaQ0hzQjhP
            VmFNaVZ1VDc4eFNUNCticlZIYk9vZ3l6bWkwClJqRGFTRFhlRGNKcTErTVdwaExW
            VmtDWWwxYzVrS0l4N3dTL1FqNkk3dlkKLS0tIDh1bUFwMjVHM1VDK3F6VUpYQWtO
            Y0k0UUFrK21sLzBpZnBTOXA1LzZHUlEKPl6NqCIaQgkHMDSaBE/DCPyRBHY/KjvC
            IhOYfInFOagH2vdSsCXtrarfwZkd8kpGzu4m5B+5Tfh0n2swvSbYZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwn0l05325gc4p827dgqw5s0k38an0cuum87pj2359ugyd0rhc6s50yqn9
    lastmodified: "2026-09-09T08:09:55Z"
    mac: ENC[AES256_GCM,data:NMjfrqX3YH+ghkc3ySJ0BItflAF9pe7OJqKsaLuxFrxNtasio7qpR03lRq19CACZJxQBM3nfAXVzx0YLmPuBpl9ckzEvTCscfMLULP/503N82rBjTYkH3DhSbDmb/tXjougl1qW1N8GJEGPMgAOJHpOIN3FWYMMkjtEthjBm1bc=,iv:dvDMvxnT76BPT3Fo4gXNukreHmcwWVSNxOlbujOvnro=,tag:DSL1FnGqrmFpjABGEzHzAw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
