apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:IKV5Gn6gp7V5Ys2eW1gGU56Xa5DGHyKX+puClnrMeLXIrI+wg7JVIlC7jIkiRySy7qd2WNl9wEbq63BNgcrAiQA1AkIkjzNd0kcS5OySHo24y+rRYVITQDaslIwg0215dfNtBc4WLT7D6GMUwC16r6/nvbvtRBwjLwYpmeZsIIqzX0P9/qEgNdI+Wc94lIMIM4hI9a3bEr4o/gHlr2FUOy3lb4MVmB/MtEqjU7Hob8/ocEjy,iv:FW/DHH15DJsIi/1Sez4LGhRQNfJIMnY3dsaXWWaT1Fs=,tag:2opznLcNuZWgYxlPdDZ6vQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWXBBSjFMZzJNYWpNbWtW
            dTZmdmYrbzVOWlcvUHl1UnZmczVhbHBweEhvCnFmcTZVekNKaFp2c2duZUpkY1c0
            N1I3WWg2VXYzalVpR2hQQ1dlZm5ZencKLS0tIHk1eTllUC8xSFc1bDJIclR6UTY0
            cU9sRzFrSDNBaFA4TS9mN2JYZ2VVR0EKMPWJ/GtBitdPRZY5EJxW3e98VNyu80cE
            1b8LGKFCF42vLfCTOC83ZJ69MNWBcxNquE+aV6mfP/XDylHSnBQ3/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwn0l05325gc4p827dgqw5s0k38an0cuum87pj2359ugyd0rhc6s50yqn9
    lastmodified: "2026-09-08T21:09:44Z"
    mac: ENC[AES256_GCM,data:foV4a2ZwbPJM43Petka34YQnkuMAGluSvXD6oeIOKYDOleIB/IfqOB76vI4JDILK95Pm/euIeiSfMqYHaywZ2P+DJx/iOQR0KylXY1dKgIDAk4forzDfzU6K9qKtYcdlJYVDMve4Z2Pc2ZYHRmr4MevSDCiWNvUxO/KlqMx8yd4=,iv:OOFsM+vbqQk8KfhYQEOutPG4vjk6+IuNFPAF5iB6+40=,tag:LR2vc5OKdanTpUADg+RMDA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
