apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
type: Opaque
stringData:
    admin.password: ENC[AES256_GCM,data:y4utzzOzivUQalrCVyBB2l9Bu89GYvC2ekpuYJmLaZnyZIaR8oebWJlZMmBB7zIrZdnLy99pSzUoXvH0,iv:6dQ09JRbN7NWB8EkXoBhqFQwnBbEu7wxP+ZU5hcFHT0=,tag:8xATEzUdHOAz2kZBzZMzNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L1kzOUlhdnZzaHo5M3JJ
            NUtCNUdrcUcxVVM1OWFCOWFmRGh2ZDcvYWdBCmlWeUNQSUhMSCt5ZWw4YTE3a252
            bFVwWDJ0Y2VWVWs0eFFZd2JBWk5jbGsKLS0tIGhNZStUeDRUaXpseStubVIzcTA1
            NVUyMURPZ1RadFkzc2JRUjNwb3NZWEEKfjFkwjdu1rzY1GySX7BEPtGSdyfOi7jD
            KPnkPbBTr60yH8eDtiRtdCScWJtSm9/gIKPls2/ahpfZW+nqobi1QQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwn0l05325gc4p827dgqw5s0k38an0cuum87pj2359ugyd0rhc6s50yqn9
    lastmodified: "2026-09-08T20:42:56Z"
    mac: ENC[AES256_GCM,data:PSuVWUN4PUxDOMa195LKgEgi1N897BbOgTerF0LYszWevP4QD8bX3krNjntxPRjzqdtjQ8IOwgCWtvL0bXV/r1baNwrqXOqQS0u2OskLQLbzyq46sY0QuVIq9V4QdarkLzy2x/Av8lAHcFMvaDBC5X+wAZJu643X4YUk5oFMApE=,iv:vfTcmSeFtUv9ZNhUPKujpHkvKXPWyTlsPTzq3Q/fuaY=,tag:AkAgFuAjMqow1/8kbF6j1Q==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
