extends: default

ignore: |
  kubernetes/**/charts/
  kubernetes/flux-system/gotk-components.yaml
  **/.terraform/
  *.enc.yaml

rules:
  document-start: disable
  line-length:
    max: 160
  comments:
    min-spaces-from-content: 1
