apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: halite
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LucaWahlen/homelab.git
    path: kubernetes/apps/halite
  destination:
    server: https://kubernetes.default.svc
    namespace: halite
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
