apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux.yaml
  - adguardhome.yaml
  - cert-manager.yaml
  - cert-manager-issuers.yaml
  - cloudflared.yaml
  - halite.yaml
  - headlamp.yaml
  - monitoring.yaml
  - shale.yaml
