apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:HmFunl4=,iv:TDNASOkPu9kD3Ep0ewvQ8yCIbubXOgy87EHdUbijm/4=,tag:3hxORlHwbngZKUaCAZFRZg==,type:str]
    admin-password: ENC[AES256_GCM,data:jFhG9pY=,iv:T063Lxcf1ZB5ZrstAX8kfFt6OImHZC3PAJgSsQan0ZE=,tag:3ywkBev9u1uuAZ2jHv+dDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OXpiMHBzd1BzWWhLZzVK
            cDI2Q2NYYW5nZVYvR0VoVzRZNVBMb25iamlZCmtjZDJwR2VZV0R6MEhTTzRiWTk5
            aHJPdmQ0bzYxNVk4RXhzenQ2T0J3cGsKLS0tIEQ4dTJvd2kwZ3Zmb3Q3OUpGV3dz
            c0gxZ3YzM3drelBpdEFCYlJvc0J1K2MKxiQK/wrqJMRM92zpJhQwOdQZLaeFzkr5
            BB6rGq608uvxyVlPXe5T1y5hU8i3GEM63hKOvm7hjAn+bp5uSI1tNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwn0l05325gc4p827dgqw5s0k38an0cuum87pj2359ugyd0rhc6s50yqn9
    lastmodified: "2026-09-29T13:08:19Z"
    mac: ENC[AES256_GCM,data:8qax2RCjC0F++xu5PXdYPkToVrUJFoH9ADHJATFjDZOA3N2nBs2cngZBZbWf0cM8cUUzjGObiYvAkWBsm3zcDBWkUObN3Lr9+kicaXnWIoxmhFR6/3FcoQJ5aflYZLGcHK7HfWEwCwEO2bF98MoJmMoeSso0qJ1NRdtbH2WpM+Q=,iv:By/Gm9ZoTA3aInY8YoiQjYCHUx/cUBQ8m7iYhpz5wLA=,tag:Wzuv/btqBKFCGBblM0mj4w==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
