apiVersion: v1
kind: Secret
metadata:
    name: shale-admin
    namespace: shale
type: Opaque
stringData:
    SHALE_ADMIN_PASSWORD: ENC[AES256_GCM,data:GUJJmo0h9gaapuFM39YZPF77Jq4=,iv:1vIXVCJ2olqsmXZCrZurzSvDPPJwMdoVR+KTnhYlqiA=,tag:SeetSBJSw+csw4SF+OWkzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQitnZVR4N3k3T3ova3pr
            ekNTUWlRNVl0cTN3bU00V3VXb1AxL29KeEY4CnVtNXJrQ0NwQWJKYUlwNklTSWp4
            SDRpM2JhWkNWWFYwV1hlTFZMMWZ1SkUKLS0tIGlWL3VaQ1hwUjQ4bXA3MGlWZTdU
            Vzcxa3FQa1dLZElwZnVYN1pwcnF0Y1UKA4PQUz/NsnFEMIqu7Bvjgs2ZxwzwpigD
            nUWkFR1nPZO6IoUzmRDzP2nF4vXvVzrHfDcxsaDzx2U/DIarW9md1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwn0l05325gc4p827dgqw5s0k38an0cuum87pj2359ugyd0rhc6s50yqn9
    lastmodified: "2026-09-27T18:23:09Z"
    mac: ENC[AES256_GCM,data:VvjnPbGuJDiBCzTT9rhc8DTrCxzbEnwhva/H9TPXoDspd33krXiydDwHAXGwDML4SdN3gsaAEvQLUWUGeQmHdACXXTKkEw7eSq55pBfa65xB0NBcuG4jAOLD2qZctJfAiolrkqSDXB24SXmNvBeRa5zrye4gBkPhqJnHpd5ic+o=,iv:jXUvM8Fu0k97Y1Qmb+lvM3XChgwVOemrnMOHZxQe3eQ=,tag:5FGtRcXA4rIpGvcmgYqjQw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
