apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:+7C+l7/yA4OxApnyeyYjzmHr7NUj5fFC50LEGOBOMrkWBwL01XQMY1hLa1loNSxm54Uv5CilUqcXLL9VRcaoV3jOO6XSBOpRdv74wqGh4AO2SIukAD65KICwHqowmYFJhwFi5Oo/RU9AaLS7cccoD7V1P1gzIER2Xm49w02hCJA8JxXL79WsxR3kabuJIh/MUvK6KDGN/Sn0oCnNTAF9PHVLfe8yANhcjtOqnrrG7xPzoZpd,iv:bWKUh/Gp68nAaWvqyqCyA0zpRICzXoSysv9gQo7pGN4=,tag:YggYSsKq8xM7NAATcqw8Qw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUVUrMGJSRDdIeHlFUWQ0
            S0dOdDVDTUNkQW1TeWQ2VnZVemhGREV3YUZjCm1Nb0hzR3lIM2NKZkZidk55N1kr
            M3REOHpyd3JYOTVnUTZYNmhDYTd1NGMKLS0tIFlmK2VhWmRvT3N0R3NISWFIY0Y5
            TTk4L2RNKzNLME9SeDZQUlpqYTJDYkEKI/9CpYjqoCQALxjR3HQjrUfSVSSV63NY
            eLEX6uEt4GTAKRwZ1yS6VTDHfRRPYqGjLFfJBanN3+biMECFM4K9DQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwn0l05325gc4p827dgqw5s0k38an0cuum87pj2359ugyd0rhc6s50yqn9
    lastmodified: "2026-09-26T16:42:46Z"
    mac: ENC[AES256_GCM,data:WWSdQlpS5MhaYa57Jo2vScOzxyEAAO0Hz13HbLIs9NeWUuZQhc25nXCnH0pNVJRZ/P9UuG8MeMktptnjJO0XxxL+7Jv9hwKHv5n1uegBJFzkTxjBwaaVhvbwKr5wk468jytu6vx2iFet/YlYDmZI7KNix3CyAPKkludxSrqEj6k=,iv:Y5egoKWtHEHLy7Ljrl9PlckMnNgCs3upwgZCwPF72CA=,tag:/4vLpdd2Gs87WG56l6jrpQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
