apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:n6W4mkIWt4S79THFpvr8dOVWslbR60tJ1Ii3Se/rHIUPTFaBn8uW/Fne6nXRdZF13Cw1ht0ziG62oeyD+HyOeu23h9tKXkaeghtGWYXC7/x7kxVZGjgz6CV2gMz1gucLRM0DT8K9dLZU9N7UZmHHpf3yRnwjCg94gcaeD3vuU2WpYUXH98Ej4aRboBtHd+xaH+XlFR7AxsACev3o9DRS6Anum5ltA6F8ULt/ScTG76mRVEPf,iv:zTumcCXkLC+temI8gP2QIaebHvN2ibSWIQwvmnbJpuU=,tag:6/jll0/QDq0KpwixCCn/NA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbjRwN3duNUxUQnVUWU55
            b01wSmpRa2lZOU44SW9LRGY1YVJyWkVsWjNrCmtGTlBTc2Qva2R2NjVVa2RBRDRo
            a2Q0dGxkbk85VVFuWTNjYnF6TGVnak0KLS0tIG5TK0JjTm05VHZqZ2tENFJrYmkw
            czhBd0VLU1FBV0laVTZRNzc4MStQblEKQNdpyx5j18ybcJOIDC4/AmOsO0W+HNrV
            Ne1TYrsCj9xl0+twDx3YcBCBhGCklmp2lTn/y26lKuL8Z3w/JQjdeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwn0l05325gc4p827dgqw5s0k38an0cuum87pj2359ugyd0rhc6s50yqn9
    lastmodified: "2026-10-10T10:09:24Z"
    mac: ENC[AES256_GCM,data:xNxNq5QSWr7lmt2esGxDY29SBO/ZJskArPU+zbdYfAz93t2jaokTV889ye+AUK1GHF+YW4fr6W3t2g47uBfACWaDC2eMDbpCuoW8UvKH/ekHPYtkiwmtuZ242WvgZj1vZR8bzSc5gF5AnJzcAcY4SahBNzEHRNo5rhBovyzSSYQ=,iv:cPlEtl16qibJzuXAnJZtUGQqBBB3EXjXXm13r0hf2Og=,tag:9+m2dTchhgbYcJDA9be7vg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
