apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
type: Opaque
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:EAL/XI0ajZAqKfIFr6PlGz6hRiPc2ra8LX/uy5+9nkKd0BAu7ODO6DuinxQ4Pfiocgr9mK0BXHL7fYDz+5u96B2TU/fRchdKHm7BE1fHGdyymb1LF3nwhgX37sFnThh4eHq7TrrbXVQ6lfZycrnDStdpDUBXuQxg7YjmktIFggiiHoBQK72udPBCIGjy1ry2D5pkfgjhLbYlo7rm/AeJ2CI+OOIdWhtVs2hmh4AsmybjAenh,iv:UJN4v0Najr5B6pr59O9Gy7pVXyIYWOodjk8CN0FFxVA=,tag:fuTT9YBHAQ+QQJgN/F40IQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGK3ZPZUJSUU1ScWtHWTFv
            ZXBQWXMxbi9kd0pHTGdGZitvWlJsMkxrTFI4CkRrMTVyMk13eWZqVHBJeFZCVW9J
            b2I2NVV2dFd0MVhRUmh4b09PckZnNVUKLS0tIElaOFBtbDV6UlBPRTFNb3ZEL1pa
            ZDE0dFJ2eTE1a0EvREpWV2tlSlhhbncKBuTIaotxOrBwjXp8UCj7+sq4U7eSybZQ
            PYkxGs4d6IsNDD9Uo4GXUkvcKNAj0tapar37whftoycEccAf5UbWog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwn0l05325gc4p827dgqw5s0k38an0cuum87pj2359ugyd0rhc6s50yqn9
    lastmodified: "2026-09-29T10:35:51Z"
    mac: ENC[AES256_GCM,data:dpnNbOw0apF64DwNjZZxV1ANyTsNRnzA8MImxvsy/ORm0L8N55Dd3mP2SqIvia9t4tD4acp3e5YG9fxi4FYAhp4Tp5k0qJ2yH6QTQk35wQogBDIkENCIKFMnDfkGCfrIOXrhCvDPHWE+8ITWEo2sG0QxVAyKonFpzijDIFjhyNs=,iv:OKLAb0wYK6otYGxYXQoJzLBPSmOS/aZNEHd/EKqtZfM=,tag:868xVrCIMc7VmyFIkfY5sw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
