apiVersion: v1
kind: Secret
metadata:
    name: adguardhome-config
    namespace: adguardhome
type: Opaque
stringData:
    AdGuardHome.yaml: ENC[AES256_GCM,data:Qi9sFyCz1GlrOTWSvfI607xGfaxGEQsXqUIxrudQt1xEWOwzPK/q30lAOSfmTEP62Mr25+1U2dPzwcrE+LfILWi5c7qZ2WJWv7tO4GOjbr3w+NJXBLupNyPR4ByPHJFgFdXw9We4KUgw+CirX1+DqQbe2sR/mLGc1XWgQiUghYsHCPz1aT5sq+KTeehteeT4ICMW9DfjjLGsunjC0/eGsECdKUgkQbcTA5t+6qXe7gq55ukhG75zbk4mrs9HF7pEI5NdjW04cZJXg/QzKFi8vNXRC4wc02KqkURenXO0iWOCs3f8YGcTKPmZXseiviTKtwl/jv1fG/fhhvnklrtlbE9bjvjzjZxStXfmcA8QovuDGmZenPNoNodrvL7OarkoD/qYWAJMRCJC1u15hGF/HCnrnaLK3Ek0kvc4JEwgJg54a0tCE/+FqfVuY9IaeYg9mKj3tSl51en0bijnd0swRuzzpNSbXHJq8yEZo/yeDHpZg4croVsapiIZaUgg+3quNgULfiYCBMV0+VxR1dQ2cdEOGNKoLiXREQW/chtlPxaBi/YhdHVjLdMWEDCl6lFj0G70MwKWpI8bQAOqe0UkqfIhNM2wc68zFBPhVCPugNZRKGl2Z8EjqXq9Tfrd/CSvihQaHnoijDtRhGPOTX1NW/2ABpDvhSqbv3qa2p/c+ejGUMZV1mxQXnq7Gu7hWH4qfqE/1wRL6ZVkQonL20c6HjCvrm5GBqedVsPfXn615OoPAN/UEDHIUiMg532mqA==,iv:vrstGl3UIvRuKNDf76x6cr6ag/EkprAqTGUTkvy6l7c=,tag:F6smqDO3OdP0g7dAAPRhTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TEc4Nnl4cUVkNGl6cFhK
            Y2RkLzV4eCttMi9yS3I1Q2Q3WnJSRDAwZ25NClRLanBVZzdOMm84QzcyVy83NjRr
            dE54SlhyVzJnZkVrN2FTSGc1UERRbHcKLS0tIG9pYzRjcnhCYmJUSkFwRkU2NU9z
            dGNHKzlLNGIxcEhBeFlYNURZZ2lIeXMKW/rynEhoolF8cX6Q31HEAbseCYPW3aTl
            Lz3S488za1LLaecRIGJdPkNoa9GHcTdmt3Cyuxiyf4QsiyW2HpHPmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwn0l05325gc4p827dgqw5s0k38an0cuum87pj2359ugyd0rhc6s50yqn9
    lastmodified: "2026-09-26T16:36:19Z"
    mac: ENC[AES256_GCM,data:mEldZoDls23Ah3yA6kAq1063HY9n5DA4lrxH/0nyzvP5TW6F8m6SFuwJEJNAWaZJRPC/YynQ9hhrC3V1rhUX2djZlfwH7uAp6U/p9cyaKtc11g1eT4woAVx2koZoF4O8CmVbLql978semzCShCgb61CLInfRjjOv22whQJ29mnY=,iv:i048mFZQYVaqI6R6DWrG6IJUf8VIOfTxfefVr2UHS4Y=,tag:BENcJiKQovNvjS0+Dr4UjQ==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
